### ISSUE TITLE
Investigate use of RAD library

### ISSUE THREAD

**Issue by redconfetti** [redconfetti/ruby-arduino-development#1]
Explore using the [rad gem](https://github.com/atduskgreg/rad)

**Comment by redconfetti** [comment]
```
$ rad hula
Successfully created your sketch directory.
Installed RAD into hula/vendor/rad

Successfully created your libraries directory.
Installed AF_XPort into hula/vendor/libraries

Installed AFSoftSerial into hula/vendor/libraries

Installed DS1307 into hula/vendor/libraries

Installed FrequencyTimer2 into hula/vendor/libraries

Installed I2CEEPROM into hula/vendor/libraries

Installed LoopTimer into hula/vendor/libraries

Installed OneWire into hula/vendor/libraries

Installed Servo into hula/vendor/libraries

Installed Stepper into hula/vendor/libraries

Installed SWSerLCDpa into hula/vendor/libraries

Installed SWSerLCDsf into hula/vendor/libraries

Installed Wire into hula/vendor/libraries

Successfully created your examples directory.
Installed examples into hula/examples

Successfully created your plugins directory.
Installed Default plugins into hula/vendor/plugins

Successfully created your default sketch directory.
Added hula/hula.rb
Added hula/Rakefile
Added hula/config
Added hula/config/hardware.yml
Added hula/config/software.yml

Run 'rake -T' inside your sketch dir to learn how to compile and upload it.
***************************************************
***     Please note: This version supports      ***
***            Arduino 12 only!                 ***
***   run rad install arduino to upgrade        ***
***************************************************
```

## Arduino Uno r3

![image](https://cloud.githubusercontent.com/assets/746759/11083063/136effd6-87e8-11e5-89a9-2a917aebf900.png)

![image](https://cloud.githubusercontent.com/assets/746759/11083076/46278bfa-87e8-11e5-8c63-434902ea8a0f.png)

**Comment by redconfetti** [comment]
Downloading the [ARDUINO 1.6.6 IDE](https://www.arduino.cc/en/Main/Software)

I donated $5, this [Download](https://www.arduino.cc/download_handler.php) link might work.

[RAD Wiki](https://github.com/atduskgreg/rad/wiki)

**Comment by redconfetti** [comment]
I was specifically concerned above about this message. I assumed it meant which version of Arduino works with the Arduino Uno r3 we're using.

```
***************************************************
***     Please note: This version supports      ***
***            Arduino 12 only!                 ***
***   run rad install arduino to upgrade        ***
***************************************************
```

I probably just need to make sure to run the upgrade command (that I missed).

**Comment by redconfetti** [comment]
Implemented changes to hula.rb to use test LED blinking configuration (on pin 13).

I guess this is how you compile your code and upload it to your device.
```
rake make:upload
```

**Comment by redconfetti** [comment]
We're not yet uploading this to the device. We need to configure a breadboard with a resistor for a simple LED circuit.

Looks like I need to install Arduino for Mac, which is likely better to do than using the download from the Arduino website. Or perhaps it's not the IDE you use to edit code.


```
$ rad install arduino
Downloading arduino-0012 for Mac from Arduino.cc
/Users/redconfetti/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: http://www.arduino.cc/files/arduino-0012-mac.zip -> https://www.arduino.cc/files/arduino-0012-mac.zip (RuntimeError)
	from /Users/redconfetti/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /Users/redconfetti/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /Users/redconfetti/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/gems/rad-0.3.0/bin/rad:101:in `block in <top (required)>'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/gems/rad-0.3.0/bin/rad:99:in `open'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/gems/rad-0.3.0/bin/rad:99:in `<top (required)>'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/bin/rad:23:in `load'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/bin/rad:23:in `<main>'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/bin/ruby_executable_hooks:15:in `eval'
	from /Users/redconfetti/.rvm/gems/ruby-2.2.1@ruby-arduino-development/bin/ruby_executable_hooks:15:in `<main>'
```

> And RAD will do its best to get the Arduino software installed on your system.

Okay, well it tried.

**Comment by redconfetti** [comment]
Since the RAD gem hasn't been maintained in so long, we're going to ditch using Ruby for now. I'm going to simply follow the instructions in [Getting Started with Arduino v3](http://www.makershed.com/products/make-getting-started-with-arduino-3rd-edition)
